stages:
  train_lr:
    cmd: uv run python -m prodml.train --model lr
    deps:
      - src/prodml
      - data/green_tripdata_2024-01.parquet
      - pyproject.toml
      - uv.lock

  train_xgboost:
    cmd: uv run python -m prodml.train --model xgboost
    deps:
      - src/prodml
      - data/green_tripdata_2024-01.parquet
      - pyproject.toml
      - uv.lock

  train_mlp:
    cmd: uv run python -m prodml.train --model mlp
    deps:
      - src/prodml
      - data/green_tripdata_2024-01.parquet
      - pyproject.toml
      - uv.lock


  tune_xgboost:
    cmd: uv run python -m prodml.tuning
    deps:
      - src/prodml
      - data/green_tripdata_2024-01.parquet
      - pyproject.toml
      - uv.lock
